bind [::]:5353
server 1.1.1.1
server 8.8.8.8
server-tcp 1.1.1.1
server-tcp 8.8.8.8
cache-size 8192
cache-persist yes
log-level info
log-file /dev/stdout
speed-check-mode ping,tcp:80,tcp:443
dualstack-ip-selection yes
redirect :53
nameserver /gfwlist.txt/127.0.0.1:5300
nameserver /china_domain.txt/-
whitelist-ip /china_ip.txt/-
conf-file /config/smartdns/list/gfwlist.txt
conf-file /config/smartdns/list/china_domain.txt
conf-file /config/smartdns/list/china_ip.txt
